version: '3.8'

services:
  mysql-db:
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: exporter
      MYSQL_PASSWORD: bochra
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - devops_network

  spring-app:
    depends_on:
      - mysql-db
    image: bochraallagui/tp-foyer-devops:5.0.0
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
               "spring.datasource.url": "jdbc:mysql://mysql-db:3306/db?createDatabaseIfNotExist=true",
               "spring.datasource.username": "root",
               "spring.datasource.password": "mysql"
             }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - devops_network

  mysql-exporter:
    image: prom/mysqld-exporter:v0.12.1
    restart: unless-stopped
    container_name: mysql-exporter
    environment:
      DATA_SOURCE_NAME: "exporter:bochra@tcp(mysql-db:3306)/"
    ports:
      - "9105:9104"
    networks:
      - devops_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - devops_network

volumes:
  db:

networks:
  devops_network:
    driver: bridge
