version: '3.8'
services:
  mysql-db:
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_DATABASE: "db"
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
  app-angular:
    depends_on:
      - spring-app


    build: ./../foyer

    ports:
      - "4200:4200"
    restart: on-failure

  spring-app:
    depends_on:
      - mysql-db

      # build: ./

    image: yousse201/tp-foyer-devops:5.0.0
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
               "spring.datasource.url": "jdbc:mysql://mysql-db:3306/db?createDatabaseIfNotExist=true",
               "spring.datasource.username": "root",
               "spring.datasource.password": "mysql"
             }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
