version: '3.8'

services:
  mysql-db:
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: mysql  # Replace with your actual password
      MYSQL_DATABASE: db
      MYSQL_USER: exporter       # Add the exporter user directly here
      MYSQL_PASSWORD: bochra     # Password for exporter user
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - devops_default

  spring-app:
    depends_on:
      - mysql-db
    image: bochraallagui/tp-foyer-devops:5.0.0
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
               "spring.datasource.url": "jdbc:mysql://mysql-db:3306/db?createDatabaseIfNotExist=true",
               "spring.datasource.username": "root",
               "spring.datasource.password": "mysql"
             }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - devops_default

  mysql-exporter:
    image: prom/mysqld-exporter:v0.12.1
    restart: unless-stopped
    container_name: mysql-exporter
    environment:
      DATA_SOURCE_NAME: "exporter:bochra@tcp(mysql-container:3306)/"
    ports:
      - "9104:9104"
    networks:
      - devops_default

volumes:
  db:

networks:
  devops_default:
    driver: bridge
